var featuredAmenitiesFullList = [
    'Free Wifi',
    'Free wired Internet',
    'Free Babysitting',
    'Babysitting with surcharge',
    'Free children club',
    'Children club with surcharge',
    'Accessible bathroom',
    'Braille signage',
    'Equipment for deaf',
    'Accessible rooms',
    'Accessible parking',
    'Accessible path of travel',
    'Roll in shower',
    'Elevator',
    'Allergy friendly',
    'Business center',
    'Free newspaper',
    'Free breakfast',
    'Fitness facilities',
    'Health club',
    'Spa',
    'Sauna',
    'Concierge service',
    'Dry cleaning',
    'Hair salon',
    'Private pool',
    'Private indoor pool',
    'Terrace',
    'Rooftop terrace',
    'Free airport pickup',
    'Free airport dropoff',
    'Free parking',
    'Paid parking',
    'Free valet parking',
    'Paid valet parking',
    'Garden',
    'BBQ grills',
];

var roomAmenitiesFullList = [
    'Balcony',
    'Terrace',
    'Patio',
    'Bathtub',
    'Hot tub',
    'Jetted tub',
    'Ensuite',
    'Connecting rooms',
    'Fireplace',
    'No windows',
    'Kitchenette',
    'Kitchen',
    'Microwave',
    'Refrigerator',
    'Refrigerator & microwave',
    'Private bathroom',
    'Two bathrooms',
    'Shared bathroom'
];

var viewsFullList = [
    'Bay View',
    'Beach View',
    'Canal View',
    'City View',
    'Courtyard View',
    'Garden View',
    'Golf View',
    'Harbor View',
    'Hill View',
    'Lagoon View',
    'Lake View',
    'Marina View',
    'Mountain View',
    'Multiple View',
    'No View',
    'Ocean View',
    'Park View',
    'Partial Lake View',
    'Partial Ocean View',
    'Partial Sea View',
    'Partial View',
    'Pool View',
    'Resort View',
    'River View',
    'Sea View',
    'Valley View',
    'View',
    'Vineyard View'
];

var standardizedAmenities = {
  "amenities": [
    "24HourCheckin",
    "QualityWiFi",
    "CableTV",
    "Books",
    "BoardGames",
    "Guidebooks",
    "ElectricalAdapters",
    "AirportTransfert",
    "HairDryer",
    "PremiumBedding",
    "Parking",
    "Roof terrace",
    "PrivatePool"
  ]
};
